CREATE TABLE APOTHIKI
(
KE int IDENTITY(1,1) NOT NULL,
EIDOS varchar(50) NULL, 
KATIGORIA varchar(10) NULL,
APOTHEMA int NULL,
TIMI_POLHSHS money NULL,
FPA real NULL,
CONSTRAINT PK_APOTHIKI PRIMARY KEY (KE)
);