CREATE TABLE PARAGELIA
(
KOD_PAR int IDENTITY(1,1) NOT NULL,
HMER_PARAGELIAS smalldatetime NULL, 
K_PEL int NULL,
TROPOS_PLHROMHS varchar(10) NULL,
TROPOS_PARADOSHS varchar(10) NULL,
CONSTRAINT PK_PARAGELIA PRIMARY KEY (KOD_PAR)
);