CREATE TABLE PELATES
(
KOD_PELATH int IDENTITY(1,1) NOT NULL,
EPONYMIA varchar(50) NULL, 
EPITHETO varchar(20) NULL,
ONOMA varchar(10) NULL,
HM_GENNISIS smalldatetime NULL,
HLIKIA int NULL,
AFM varchar(10) NULL,
DOY varchar(10) NULL,
DIETHINSI varchar(10) NULL,
POLH varchar(10) NULL,
THL varchar(10) NULL,
FOTO varchar(200) NULL,
SXOLIA varchar(50) NULL,
CONSTRAINT PK_PELATES PRIMARY KEY (KOD_PELATH)
);